### ISSUE TITLE
Issue with interpolation following attribute selector

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#198] opened 2016-07-13 10:49 UTC
Currently the following will return a parse error due to a problem with interpolation following an attribute selector. The problem is not limited to the `&` and only occurs when there is no space between the attribute selector and interpolation.

``` sass
// Raises a problem

[type=email]#{&} {
  border: 1px solid blue;
}

.foo[type=email]#{$bar} {
  border: 1px solid blue;
}

input[type=email]#{$baz} {
  border: 1px solid blue;
}
```

``` sass
// Is ok

[type=email] #{&} {
  border: 1px solid blue;
}

.foo[type=email] #{$bar} {
  border: 1px solid blue;
}

input[type=email] #{$baz} {
  border: 1px solid blue;
}
```

Reported in https://github.com/sasstools/sass-lint/issues/786

**Comment by tonyganch** [comment] 2016-08-02 11:28
I guess the issue is closed by merging #200 into `dev`.

**Closed as completed by tonyganch** 2016-08-02 11:28 UTC
Labels: type: bug, syntax: sass, syntax: scss, status: fixed
