### ISSUE TITLE
css variables

### ISSUE THREAD

**Issue by cancerberoSgx** [tonyganch/gonzales-pe#262] opened 2017-03-16 20:27 UTC
Please support css variables like this: 

```

var css = ':root {\n	--color1: red;\n}'
var parseTree = parser.parse(css)

```

https://www.w3.org/TR/css-variables/

Thanks!, incredible project BTW !! :) :)

**Comment by tonyganch** [comment] 2017-03-21 11:56
Hi @cancerberoSgx, I'm closing this issue as a duplicate of #197, please subsсribe there for updates.

**Closed as completed by tonyganch** 2017-03-21 11:56 UTC
Labels: type: duplicate
