### ISSUE TITLE
Cannot parse scss variables with "url" in the name with a comment following

### ISSUE THREAD

**Issue by dane-harnett** [tonyganch/gonzales-pe#95] opened 2015-09-19 06:07 UTC
Parse error occurs on the following snippet:

```
$a-url: 'myUrl.png';
// comment

```

**Comment by DanPurdy** [comment] 2015-09-28 17:55
Hi there, 
I'm also seeing something similar. Currently seeing some strange parse error with certain selector names when comments are present within a block

``` scss
.url-overflow {
  // this is a comment
  content: '';
}
```

Interestingly no parse error is present for the following:

``` scss

// no - in selector name
.urloverflow {
  // this is a comment
  content: '';
}

//no use of url in selector name
.test-overflow {
  // this is a comment
  content: '';
}

//no comment within block
.url-overflow {
  content: '';
}
```

The only thing having changed is the name of the selector removing a `-` though if the selector doesn't contain the word url with that symbol it acts perfectly fine.

The error is always reporting on the line with the comment though and removing the comment from the block also reports no parse error.

This was originally reported here
https://github.com/sasstools/sass-lint/issues/229

If you need any more information let me know.

Thanks!

**Comment by tonyganch** [comment] 2015-10-18 02:07
@dane-harnett @DanPurdy, I think the issue has been fixed with #104.
I've added tests for both of your examples above and they pass.
Please check `dev` branch or `@3.0.2` version and let me know if you find that the issue is still there.

**Closed as completed by tonyganch** 2015-10-18 02:07 UTC

**Comment by DanPurdy** [comment] 2015-10-19 21:45
Hi @tonyganch I've just run the original issue and the code I posted above against 3.2.1 and all is fine. Thanks!
