### ISSUE TITLE
Issue w/ atom linter-sass-lint

### ISSUE THREAD

**Issue by mikeerickson** [tonyganch/gonzales-pe#216] opened 2016-08-18 23:27 UTC
I am running into an issue w/ the Atom plugin "linter-sass-lint" and he is claiming it is your issue?  

You can gain complete info here 

https://github.com/AtomLinter/linter-sass-lint/issues/135

**Comment by DanPurdy** [comment] 2016-08-18 23:35
Hi again @mikeerickson,

It's throwing a parse error so you need to provide the code that is failing and why you think it's failing if you know or at least some information.

It's almost definitely going to be a duplicate of this though https://github.com/tonyganch/gonzales-pe/issues/204

I wasn't claiming, I was telling you the exact issue! 😄 😛  
please in future try to be a bit more descriptive or search existing issues first, thanks!

closing as duplicate

**Closed as completed by DanPurdy** 2016-08-18 23:35 UTC

**Comment by mikeerickson** [comment] 2016-08-18 23:52
Yes sir!

FTR, my initial report included a screenshot of what was happen.  Further this only occurs in atom, if I lint via CLI no errors

**Comment by DanPurdy** [comment] 2016-08-19 00:07
Hmm, there must be an issue with the files you're including when using the CLI or how you're using the CLI then as the atom plugin doesn't do anything apart from call sass-lint and consume its output much in the same way you do when you use the CLI. This is a known issue with gonzales-pe at the moment and however it gets parsed in sass-lint it would always throw a parse error if that file is encountered. You can confirm this by testing the code yourself if you wish in the playground http://tonyganch.com/gonzales-pe/ you'll see it always returns empty which indicates a parse error.

My reason for asking for the info above is just to make it as simple as possible for someone to be able to help you with your issue by providing them as much useful information as you can within the issue, gonzales-pe is used in other projects as well as sass-lint and therefore contributors won't necessarily know what they're looking at with sass-lint or linter-sass-lint specific issues. 

Will look into this for you though. 

Thanks!

**Comment by mikeerickson** [comment] 2016-08-20 23:24
@DanPurdy I have already moved on from this issue, seeing as there doesn't seem to be a desire to fix the issue.  Having said that, in response to your request.  If you want more information or just assume it is my fault, let me know 

CLI call

```
"sass-lint": "sass-lint \"../ci-components/app/components/gmail-addin/*.sass\" -q -v",
```

You can see that one of the .sass files in this above defined path is throwing the error within atom 
- screenshot 1
  Shows the error from atom
- screenshot 2
  Shows the path to the file in question (and see that it matches the CLI glob

<img width="573" alt="sass-lint-atom-1" src="https://cloud.githubusercontent.com/assets/183153/17834370/6ce6e9a4-66f2-11e6-8268-ec8a5d56e8fc.png">
<img width="711" alt="sass-lint-atom-2" src="https://cloud.githubusercontent.com/assets/183153/17834369/6ce62fc8-66f2-11e6-9715-2f823746b8d4.png">
